module.exports = {
  NEW_CHAT_INIT: 'NEW_CHAT_INIT',
  NEW_CHAT_SUCCESS: 'NEW_CHAT_SUCCESS',
  NEW_CHAT_FAILED: 'NEW_CHAT_FAILED',
  SEND_MESSAGE_INIT: 'SEND_MESSAGE_INIT',
  SEND_MESSAGE_SUCCESS: 'SEND_MESSAGE_SUCCESS',
  SEND_MESSAGE_FAILED: 'SEND_MESSAGE_FAILED',
  SAVE_MESSAGE_INIT: 'SAVE_MESSAGE_INIT',
  SAVE_MESSAGE_SUCCESS: 'SAVE_MESSAGE_SUCCESS',
  SAVE_MESSAGE_FAILED: 'SAVE_MESSAGE_FAILED'
}
