/* eslint-disable import/no-anonymous-default-export */
export default {
  USER_REGISTER: 'USER_REGISTER',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILED: 'USER_REGISTER_FAILED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILED: 'USER_LOGIN_FAILED',
  USER_LOCATION_REQUESTED: 'USER_LOCATION_REQUESTED',
  USER_LOCATION_SUCCESS: 'USER_LOCATION_SUCCESS',
  USER_LOCATION_FAILED: 'USER_LOCATION_FAILED'
}
